spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cyber-todo-admin-db?serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: wy123456
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    filters: stat,wall,log4j
    initialSize: 20
    maxActive: 2000
    maxPoolPreparedStatementPerConnectionSize: 20
    maxWait: 60000
    minEvictableIdleTimeMillis: 300000
    minIdle: 500
    poolPreparedStatements: true
    testOnBorrow: false
    testOnReturn: false
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    useGlobalDataSourceStat: true
    validationQuery: SELECT 'x'
    druid:
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: wy123456
  # ==================security配置==================
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 44dc283f00fc039c8eac
            client-secret: 4c70c2c794b32547892dd2607b97ce6473db73c2
  #    user:
  #      name: user
  #      password: $2a$10$y/.2k6wPmRED4h/3oyKtUuX1uTKHs9HFOEAf96eSd9OmIqpdso1De
  #  ==================jedis 客户端配置==================
  #  data:
  #    redis:
  #      host: localhost
  #      port: 6379
  #      database: 0
  #      jedis:
  #        pool:
  #          min-idle: 0
  #          max-idle: 8
  #          max-wait: -1ms
  #          max-active: 200
  #      connect-timeout: 1000ms
  elasticsearch:
    uris:
      - http://localhost:9200
    username: elastic
    password: bQ*qvCFXGnpVw-tRuYrn

# 指定redisson配置文件
redisson:
  singleServerConfig:
    address: "redis://localhost:6379"
    host: "localhost"
    port: 6379
    masterName: local-redis5.0
    sentinel: "false"
    database: 0
    idleConnectionTimeout: 10000
    pingTimeout: 1000
    connectTimeout: 10000
    timeout: 10000
    retryInterval: 3000
    retryAttempts: 3
    password: null
    subscriptionsPerConnection: 5
    clientName: null
  threads: 512
  nettyThreads: 64
#  codec: !<org.redisson.codec.MarshallingCodec> { }
  transportMode: "NIO"

