spring:
  profiles:
    active: '@profile.name@'
  application:
    name: '@application.name@'
  banner:
    location: static/banner.txt
  datasource:
    druid:
      stat-view-servlet:
#        deny优先于allow;如果allow没有配置或者为空，则允许所有访问
        allow:
server:
  port: 9646
#  会话超时时间
  servlet:
    session:
      timeout: 30m

mybatis-plus:
  check-config-location: true
#  不能同时使用配置类和配置文件
#  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath*:com/wy/cybertodoadmin/**/mapper/*Mapper.xml
  configuration:
    cache-enabled: false
    default-executor-type: reuse
    default-statement-timeout: 25000
    jdbc-type-for-null: 'null'
    lazy-loading-enabled: true
    local-cache-scope: statement
    map-underscore-to-camel-case: true
    multiple-result-sets-enabled: true
    use-column-label: true
  global-config:
    db-config:
      id-type: auto
      table-underline: true
#springdoc相关配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'hyc'
      paths-to-match: '/**'
      packages-to-scan: com.hyc  #改成你自己的包名，一般到启动类的包名

#knife4j相关配置 可以不用改
knife4j:
  enable: true
  setting:
    language: zh_cn


